name: dart_sha2_test
description: Testing my own SHA2 implementation in Dart using FFI.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  ffi: ^2.1.5
  crypto: ^3.0.7
  convert: ^3.1.2
  ansicolor: ^2.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
